-- MySQL Script generated by MySQL Workbench
-- 07/13/15 23:05:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema webshop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `webshop` ;

-- -----------------------------------------------------
-- Schema webshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webshop` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `webshop` ;

-- -----------------------------------------------------
-- Table `webshop`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`clients` ;

CREATE TABLE IF NOT EXISTS `webshop`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `cpf` VARCHAR(12) NOT NULL COMMENT '',
  `telephone` VARCHAR(14) NOT NULL COMMENT '',
  `password` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`products` ;

CREATE TABLE IF NOT EXISTS `webshop`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `desc` VARCHAR(255) NOT NULL COMMENT '',
  `price` DECIMAL(2) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`adresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`adresses` ;

CREATE TABLE IF NOT EXISTS `webshop`.`adresses` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `desc` VARCHAR(45) NOT NULL COMMENT '',
  `street` VARCHAR(45) NOT NULL COMMENT '',
  `number` INT NOT NULL COMMENT '',
  `bairro` VARCHAR(25) NOT NULL COMMENT '',
  `city` VARCHAR(25) NOT NULL COMMENT '',
  `zip` VARCHAR(8) NOT NULL COMMENT '',
  `clients_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `clients_id`)  COMMENT '',
  INDEX `fk_enderecos_clientes1_idx` (`clients_id` ASC)  COMMENT '',
  CONSTRAINT `fk_enderecos_clientes1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `webshop`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`orders` ;

CREATE TABLE IF NOT EXISTS `webshop`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `data_order` DATETIME NOT NULL COMMENT '',
  `data_mod` DATETIME NOT NULL COMMENT '',
  `status` VARCHAR(15) NOT NULL COMMENT '',
  `price_products` DECIMAL(2) NOT NULL COMMENT '',
  `price_shipping` DECIMAL(2) NOT NULL COMMENT '',
  `discounts` DECIMAL(2) NOT NULL COMMENT '',
  `clientes_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `clientes_id`)  COMMENT '',
  INDEX `fk_pedidos_clientes1_idx` (`clientes_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `webshop`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`orders_has_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`orders_has_products` ;

CREATE TABLE IF NOT EXISTS `webshop`.`orders_has_products` (
  `orders_id` INT NOT NULL COMMENT '',
  `products_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`orders_id`, `products_id`)  COMMENT '',
  INDEX `fk_pedidos_has_produtos_produtos1_idx` (`products_id` ASC)  COMMENT '',
  INDEX `fk_pedidos_has_produtos_pedidos_idx` (`orders_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pedidos_has_produtos_pedidos`
    FOREIGN KEY (`orders_id`)
    REFERENCES `webshop`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_produtos_produtos1`
    FOREIGN KEY (`products_id`)
    REFERENCES `webshop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
