-- MySQL Script generated by MySQL Workbench
-- 07/09/15 22:30:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema webshop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `webshop` ;

-- -----------------------------------------------------
-- Schema webshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webshop` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `webshop` ;

-- -----------------------------------------------------
-- Table `webshop`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`clientes` ;

CREATE TABLE IF NOT EXISTS `webshop`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `cpf` VARCHAR(12) NOT NULL COMMENT '',
  `telefone` VARCHAR(14) NOT NULL COMMENT '',
  `senha` VARCHAR(15) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`produtos` ;

CREATE TABLE IF NOT EXISTS `webshop`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `desc` VARCHAR(255) NOT NULL COMMENT '',
  `valor` DECIMAL(2) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`enderecos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`enderecos` ;

CREATE TABLE IF NOT EXISTS `webshop`.`enderecos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `desc` VARCHAR(45) NOT NULL COMMENT '',
  `rua` VARCHAR(45) NOT NULL COMMENT '',
  `numero` INT NOT NULL COMMENT '',
  `bairro` VARCHAR(25) NOT NULL COMMENT '',
  `cidade` VARCHAR(25) NOT NULL COMMENT '',
  `cep` VARCHAR(8) NOT NULL COMMENT '',
  `clientes_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `clientes_id`)  COMMENT '',
  INDEX `fk_enderecos_clientes1_idx` (`clientes_id` ASC)  COMMENT '',
  CONSTRAINT `fk_enderecos_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `webshop`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`pedidos` ;

CREATE TABLE IF NOT EXISTS `webshop`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `data_compra` DATETIME NOT NULL COMMENT '',
  `data_mod` DATETIME NOT NULL COMMENT '',
  `status` VARCHAR(15) NOT NULL COMMENT '',
  `valor_produtos` DECIMAL(2) NOT NULL COMMENT '',
  `valor_frete` DECIMAL(2) NOT NULL COMMENT '',
  `descontos` DECIMAL(2) NOT NULL COMMENT '',
  `clientes_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `clientes_id`)  COMMENT '',
  INDEX `fk_pedidos_clientes1_idx` (`clientes_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `webshop`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`pedidos_has_produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`pedidos_has_produtos` ;

CREATE TABLE IF NOT EXISTS `webshop`.`pedidos_has_produtos` (
  `pedidos_id` INT NOT NULL COMMENT '',
  `produtos_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`pedidos_id`, `produtos_id`)  COMMENT '',
  INDEX `fk_pedidos_has_produtos_produtos1_idx` (`produtos_id` ASC)  COMMENT '',
  INDEX `fk_pedidos_has_produtos_pedidos_idx` (`pedidos_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pedidos_has_produtos_pedidos`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `webshop`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_produtos_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `webshop`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
